---
# Source: scec-vulnerability/templates/cronjob.yaml
# Copyright (c) 2021 Linux Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scec-vulnerability
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/os: linux
          containers:
            - name: scec-vulnerability
              image: "quay.io/ortelius/scec-vulnerability:main-v10.0.92-g2eebd3"
              imagePullPolicy: IfNotPresent
              env:
                - name: ARANGO_USER
                  valueFrom:
                    secretKeyRef:
                      name: arangodb
                      key: DBUserName
                - name: ARANGO_PASS
                  valueFrom:
                    secretKeyRef:
                      name: arangodb
                      key: DBPassword
                - name: ARANGO_HOST
                  valueFrom:
                    secretKeyRef:
                      name: arangodb
                      key: DBHost
                - name: ARANGO_PORT
                  valueFrom:
                    secretKeyRef:
                      name: arangodb
                      key: DBPort
                - name: MS_PORT
                  value: "8080"
          restartPolicy: OnFailure
