# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: templates/
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: templates/
DISABLE_LINTERS:
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_TRIVY
  - REPOSITORY_DEVSKIM
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
DISABLE:
  - COPYPASTE
  - SPELL

GO_GOLANGCI_LINT_CLI_LINT_MODE: project
GO_GOLANGCI_LINT_ARGUMENTS: --timeout 10m
PRE_COMMANDS:
  [
    "command": "wget https://go.dev/dl/go1.22.2.linux-amd64.tar.gz",
    "command": "rm -rf /usr/lib/go",
    "command": "tar -xf go1.22.2.linux-amd64.tar.gz -C /usr/lib",
    "command": "go version",
  ]
