host: localhost:8080
info:
  contact:
    email: ortelius-dev@googlegroups.com
    name: Ortelius Google Group
  description: |-
    Vulnerabilities from osv.dev
    ![Release](https://img.shields.io/github/v/release/ortelius/scec-vulnerability?sort=semver)
    ![license](https://img.shields.io/github/license/ortelius/scec-vulnerability)

    ![Build](https://img.shields.io/github/actions/workflow/status/ortelius/scec-vulnerability/build-push-chart.yml)
    [![MegaLinter](https://github.com/ortelius/scec-vulnerability/workflows/MegaLinter/badge.svg?branch=main)](https://github.com/ortelius/scec-vulnerability/actions?query=workflow%3AMegaLinter+branch%3Amain)
    ![CodeQL](https://github.com/ortelius/scec-vulnerability/workflows/CodeQL/badge.svg)
    [![OpenSSF-Scorecard](https://api.securityscorecards.dev/projects/github.com/ortelius/scec-vulnerability/badge)](https://api.securityscorecards.dev/projects/github.com/ortelius/scec-vulnerability)

    ![Discord](https://img.shields.io/discord/722468819091849316)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ortelius v11 Vulnerability Microservice
  version: 11.0.0
paths: {}
swagger: "2.0"
